### ISSUE TITLE
name 'cur' is not defined

### ISSUE THREAD

**Issue by nazpetrov** [Oros42/IMSI-catcher#104]
Hi all!
thanks to well-known solutions, i solved some issues and get success.
but now, when i started grgsm-livemon and hex dataflow begin, in window with IMSI-catcher first line with necessary data appers and IMSI-catcher stop immediately with this error:

```
Traceback (most recent call last):
  File "simple_IMSI-catcher.py", line 612, in <module>
    sniff(iface=options.iface, filter="port {} and not icmp and udp".format(options.port), prn=find_imsi_from_pkt, store=0)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 925, in _run
    session.on_packet_received(p)
  File "/usr/lib/python3/dist-packages/scapy/sessions.py", line 47, in on_packet_received
    result = self.prn(pkt)
  File "simple_IMSI-catcher.py", line 563, in find_imsi_from_pkt
    find_imsi(udpdata)
  File "simple_IMSI-catcher.py", line 492, in find_imsi
    t.register_imsi(gsm.arfcn, imsi1, imsi2, tmsi1, tmsi2, p)
  File "simple_IMSI-catcher.py", line 278, in register_imsi
    self.pfields(str(n), tmsi1, tmsi2, imsi1, str(self.mcc), str(self.mnc), str(self.lac), str(self.cell), p)
  File "simple_IMSI-catcher.py", line 211, in pfields
    if cur:
NameError: name 'cur' is not defined
```

What i am doing:
First run 
`sudo python3 simple_IMSI-catcher.py -s`. 
then in a new window run 
`grgsm_scanner`, 
find stations. Then with this information run grgsm_livemon, for example
`grgsm_livemon -f 950.0M --args=rtl`.
Then, after up-down scrolling frequency scrollbar, i find frequency where data starts to flow. 
And then that trouble with IMSI-catcher window.

Sorry for my english and Thanks for your attention!

**Comment by nazpetrov** [comment]
Thank you!!!
