### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by greengit-05** [Oros42/IMSI-catcher#123]
When I run in 2-nd terminal, get error:

```
kali@kali:~/IMSI-catcher-master$ python simple_IMSI-catcher.py                                 
Nb IMSI ; TMSI-1     ; TMSI-2     ; IMSI              ; country      ; brand      ; operator              ; MCC  ; MNC   ; LAC    ; CellId
Traceback (most recent call last):
  File "simple_IMSI-catcher.py", line 536, in <module>
    udpserver(port=options.port, prn=find_imsi)
  File "simple_IMSI-catcher.py", line 485, in udpserver
    sock.bind(server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

```
I read [here](https://github.com/ptrkrysik/gr-gsm/issues/442) but grgsm_livemon is must be run, I can't kill them.
Also I read [here](https://github.com/Oros42/IMSI-catcher/issues/53) but it's don't help me.
Help me please to solve this problem.

**Comment by Oros42** [comment]
What did you have with :
```
sudo python3 simple_IMSI-catcher.py --sniff
```
?

**Comment by greengit-05** [comment]
Thanks! I'm enter the key --sniff under root permission and it's working OK!
