### ISSUE TITLE
Not able to detect GSM packets in Ubuntu 14.04

### ISSUE THREAD

**Issue by na0710** [Oros42/IMSI-catcher#39]
I have installed all the necessary libraries. I am not getting any IMSI number using the code simple_IMSI-catcher.py. Running the rtl_test gives - 
```
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
No supported tuner found
Enabled direct sampling mode, input 1
Supported gain values (1): 0.0 
Sampling at 2048000 S/s.

Info: This tool will continuously read from the device, and report if
samples get lost. If you observe no further output, everything is fine.

Reading samples in async mode...
```
Running grgsm_scanner gives, 
linux; GNU C++ version 4.8.2; Boost_105400; UHD_003.005.005-0-unknown 
and nothing else. 

What can be done further?

**Comment by Oros42** [comment]
What is the output of ```grgsm_scanner``` ?

**Comment by na0710** [comment]
linux; GNU C++ version 4.8.2; Boost_105400; UHD_003.005.005-0-unknown
and nothing else.

**Comment by Oros42** [comment]
Step One : update your ubuntu.
This what you should have : 
```
$ grgsm_scanner
linux; GNU C++ version 5.3.1 20151219; Boost_105800; UHD_003.009.002-0-unknown

ARFCN:    1, Freq:  XXXXXM, CID: XXXXX, LAC: XXXXX, MCC: XXX, MNC: XXX, Pwr: -27
```
If you don't have this, my program can't work.

**Comment by na0710** [comment]
So is there a need to update ubuntu or other softwares ?

**Comment by Oros42** [comment]
Update your ubuntu. It's too old.

**Comment by na0710** [comment]
Well I have tried in  different pc. 
I am not getting any output on running - `python simple_IMSI-catcher.py`
While running `python scan-and-livemon`
I am getting - 
```
Locating potential GSM base station frequencies (this can take a few minutes).
linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.010.001.HEAD-0-g929e3b32

Traceback (most recent call last):
  File "scan-and-livemon", line 101, in <module>
    main()
  File "scan-and-livemon", line 78, in main
    list = find_gsm_bases()
  File "scan-and-livemon", line 25, in find_gsm_bases
    (options, args) = scanner.argument_parser().parse_args()

```

While running `grgsm_livemon -f 938.2M`
 I am getting - 
```
linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.010.001.HEAD-0-g929e3b32

gr-osmosdr v0.1.4-98-gc653754d (0.1.5git) gnuradio 3.7.9
built-in source types: file fcd rtl rtl_tcp uhd rfspace redpitaya 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
No supported tuner found
Enabled direct sampling mode, input 1
Exact sample rate is: 2000000.052982 Hz
Could not find port: bursts in:
bursts
system

Traceback (most recent call last):
  File "/usr/bin/grgsm_livemon", line 270, in <module>
    tb = grgsm_livemon(fc=options.fc, gain=options.gain, ppm=options.ppm, samp_rate=options.samp_rate, shiftoff=options.shiftoff, args=options.args)
  File "/usr/bin/grgsm_livemon", line 143, in __init__
    self.gsm_sdcch8_demapper_0 = grgsm.gsm_sdcch8_demapper(1)
  File "/usr/lib/python2.7/dist-packages/grgsm/gsm_sdcch8_demapper.py", line 39, in __init__
    self.msg_connect((self.gsm_universal_ctrl_chans_demapper_0, 'bursts'), (self, 'bursts'))    
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 59, in wrapped
    func(self, src.to_basic_block(), srcport, dst.to_basic_block(), dstport)
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 131, in msg_connect
    self.primitive_msg_connect(*args)
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 3584, in primitive_msg_connect
    return _runtime_swig.hier_block2_sptr_primitive_msg_connect(self, *args)
RuntimeError: invalid msg port in connect() or disconnect()
```
The output of `grgsm_scanner` is - 
`linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.010.001.HEAD-0-g929e3b32`

**Comment by Oros42** [comment]
I updated the README.md. Tell me if it's better.

**Comment by na0710** [comment]
I have changed the frequency. It didn't work either.
