### ISSUE TITLE
No output by simple_IMSI-catcher.py

### ISSUE THREAD

**Issue by zoltan85000** [Oros42/IMSI-catcher#57]
Dear
despite my efforts to find myself alone, a solution, I am compelled to parasitize here.
I'm using two terminals: Terminal 1 to find one frequency (by grgsm-scanner) and after select one of these; I'm using grgsm-livemon to send GSMTAP data  format by UDP server. Terminal 2: to read UDP packet of terminal 1 by simpleIMSYCatcher.py . 
Here an example:

Terminal 1:

**VirtualBox:~$ grgsm_scanner -v -g 40**
linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

ARFCN:  980, Freq:  926.2M, CID:     0, LAC:     0, MCC:   0, MNC:   0, Pwr: -58
  |---- Configuration: Unknown
  |---- Cell ARFCNs:
  |---- Neighbour Cells:

ARFCN:   79, Freq:  950.8M, CID:  7690, LAC: 30510, MCC: 208, MNC:  10, Pwr: -60
  |---- Configuration: 1 CCCH, not combined
  |---- Cell ARFCNs:
  |---- Neighbour Cells:

**VirtualBox:~$ grgsm_livemon -g 40 -f 926.2M --serverport=4729**
Warning: failed to XInitThreads()
linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.11
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp
Cannot connect to server socket err = Aucun fichier ou dossier de ce type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Detached kernel driver
Found Rafael Micro R820T tuner
Reattached kernel driver
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Detached kernel driver
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 2000000,052982 Hz
[R82XX] PLL not locked!
Allocating 15 zero-copy buffers
 15 06 21 00 01 f0 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b
 25 06 21 00 05 f4 02 d9 01 9e 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b
 25 06 21 00 05 f4 e8 78 23 03 23 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b
 25 06 21 00 05 f4 f0 70 2e 13 23 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b
 31 06 1c 02 f8 02 01 a7 60 06 b9 00 00 80 01 47 2b 2b 2b 2b 2b 2b 2b
 01 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b
 15 06 21 00 01 f0 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b
 31 06 21 00 08 29 80 02 71 61 20 39 92 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b
 15 06 21 00 01 f0 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b
 15 06 21 00 01 f0 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b
......

2. - Terminal 2:
**VirtualBox:~/IMSI-catcher$ sudo ./simple_IMSI-catcher.py**
[sudo] Mot de passe de rolland :
Nb IMSI ; TMSI-1     ; TMSI-2     ; IMSI              ; country      ; brand      ; operator              ; MCC  ; MNC   ; LAC    ; CellId
Traceback (most recent call last):
  File "./simple_IMSI-catcher.py", line 547, in <module>
    udpserver(port=options.port, prn=find_imsi)
  File "./simple_IMSI-catcher.py", line 496, in udpserver
    sock.bind(server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
**VirtualBox:~/IMSI-catcher$ sudo ./simple_IMSI-catcher.py -s**
Nb IMSI ; TMSI-1     ; TMSI-2     ; IMSI              ; country      ; brand      ; operator              ; MCC  ; MNC   ; LAC    ; CellId

And I Have no output; May be I am wrong somewhere ?
WireShark work well.
Could you help me to find my mistake ?
Philippe,
Best regards

**Comment by zoltan85000** [comment]
Dear,
ok all is allright; no problem, it's perfect.
Thanks you for all.
Bets regards.

**Comment by Oros42** [comment]
For helping other users, could you post what you done to solve it ?

**Comment by zoltan85000** [comment]
Dear Oros42,
of course with plaisure. I'm founding this URL:  [https://www.reddit.com/r/RTLSDR/comments/721ro3/having_troubles_with_imsicatcher_warning_long_post/](https://www.reddit.com/r/RTLSDR/comments/721ro3/having_troubles_with_imsicatcher_warning_long_post/)

So I'm just add  `--args rtl ` with command `grgsm_livemon` ; for example:
`grgsm_livemon --args rtl -f xxx.xxx.xxxM  -g 40`

In return; I'm looking for how to scan more than one frequency (4 BTS for example) to send to simple_IMSI-catcher.py; do you have any idea ? Inside file [scan-and-livemon](https://github.com/Oros42/IMSI-catcher/pull/23/commits/717ce4d0dd9cd0fe28d0488d31b3d29af46ac3ea): I can see may be a solution, but I don't really understanding.

> """
> Script to scan for base stations and start submitt GSM packages on one
> or more the frequencies found using grgsm_livemon_headless to the
> loopback network device
> The idea is to gather GSM packages from as many of the GSM base
> stations and phones in the area as possible, by spreading across as
> many operators as possible.
> """

Could you help me ?
Best regards for all.

**Comment by msfu101** [comment]
I have no Output from IMSI-catcher and grgsm_scanner, too. 
But grgsm_livemon works with my Hackrf.
Is it possible that there is a conflict with Gnuradio8? Because it works fine under Gnuradio7...
Thanks in advance!

**Comment by Winter85** [comment]
I am looking for some solution regarding the script "./simple_IMSI-catcher.py" as I can add other ports so that I can collect data from several ports at the same time. Maybe someone will suggest something?

Thank you in advance for your answer.
