### ISSUE TITLE
cant assign the network interface to the BPF handle

### ISSUE THREAD

**Issue by nsklyarov** [Oros42/IMSI-catcher#68]
trying run simple_IMSI-catcher.py script on 

OS X High Sierra 10.13.6 (17G65)
Python 2.7.16
scapy 2.4.2
scipy 1.2.1
numpy 1.16.2

`sudo python simple_IMSI-catcher.py -s`

```
Traceback (most recent call last):
  File "simple_IMSI-catcher.py", line 533, in <module>
    sniff(iface=options.iface, filter="port {} and not icmp and udp".format(options.port), prn=find_imsi_from_pkg, store=0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/sendrecv.py", line 836, in sniff
    *arg, **karg)] = iface
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/bpf/supersocket.py", line 72, in __init__
    raise Scapy_Exception("BIOCSETIF failed on %s" % self.iface)
scapy.error.Scapy_Exception: BIOCSETIF failed on lo
```

found this in src scapy/supersocket.py
https://github.com/secdev/scapy/blob/master/scapy/arch/bpf/supersocket.py#L68

`sudo python immediate_assignment_catcher.py`

gives the same result..

thks for your attention

**Comment by nsklyarov** [comment]
please answer me if my question is incomprehensible

**Comment by Oros42** [comment]
Have you try ? :
```python scan-and-livemon```
(no sudo)
