### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by kjellxvx** [Oros42/IMSI-catcher#92]
After successfully running and catching I get the following error always after a few minutes. 

```
Traceback (most recent call last):
  File "simple_IMSI-catcher.py", line 538, in <module>
    sniff(iface=options.iface, filter="port {} and not icmp and udp".format(options.port), prn=find_imsi_from_pkt, store=0)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 603, in sniff
    r = prn(p)
  File "simple_IMSI-catcher.py", line 498, in find_imsi_from_pkt
    find_imsi(udpdata)
  File "simple_IMSI-catcher.py", line 429, in find_imsi
    t.register_imsi(gsm.arfcn, imsi1, imsi2, tmsi1, tmsi2, p)
  File "simple_IMSI-catcher.py", line 180, in register_imsi
    if imsi1: self.imsi_seen(imsi1, arfcn)
  File "simple_IMSI-catcher.py", line 257, in imsi_seen
    self.imsi_purge_old()
  File "simple_IMSI-catcher.py", line 262, in imsi_purge_old
    for imsi in self.imsistate.keys():
RuntimeError: dictionary changed size during iteration
```

**Comment by jbarea** [comment]
I get the error as well after a few minutes of running.
My output is this:

`Traceback (most recent call last):
  File "simple_IMSI-catcher.py", line 538, in <module>
    sniff(iface=options.iface, filter="port {} and not icmp and udp".format(options.port), prn=find_imsi_from_pkt, store=0)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 886, in sniff
    r = prn(p)
  File "simple_IMSI-catcher.py", line 498, in find_imsi_from_pkt
    find_imsi(udpdata)
  File "simple_IMSI-catcher.py", line 429, in find_imsi
    t.register_imsi(gsm.arfcn, imsi1, imsi2, tmsi1, tmsi2, p)
  File "simple_IMSI-catcher.py", line 180, in register_imsi
    if imsi1: self.imsi_seen(imsi1, arfcn)
  File "simple_IMSI-catcher.py", line 257, in imsi_seen
    self.imsi_purge_old()
  File "simple_IMSI-catcher.py", line 262, in imsi_purge_old
    for imsi in self.imsistate.keys():
RuntimeError: dictionary changed size during iteration
`
